version: "3.8"

networks:
  hcktn_network:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    container_name: hcktn_PostgreSQL
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    networks:
      - hcktn_network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: hcktn_Grafana
    ports:
      - "3000:3000"
    networks:
      - hcktn_network
    depends_on:
      - postgres
    volumes:
      - ./dashboard/data:/var/lib/grafana
    restart: unless-stopped

  jira:
    image: atlassian/jira-software
    container_name: hcktn_Jira
    ports:
      - "8080:8080"
    networks:
      - hcktn_network
    depends_on:
      - postgres
    volumes:
      - ./jira/data:/var/atlassian/application-data/jira
    restart: unless-stopped
